---
apiVersion: v1
kind: Service
metadata:
  name: mc
  labels:
    prometheus-target: memcached
spec:
  clusterIP: None
  ports:
  - name: memcached
    port: 11211
    targetPort: 11211
  - name: http-metrics
    port: 9150
    protocol: TCP
    targetPort: 9150
  selector:
    app: mc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mc
  labels:
    app: mc
spec:
  serviceName: mc
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
  replicas: {{ pluck .Values.global.env .Values.memcached.replicas | first | default .Values.memcached.replicas._default }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: mc
            topologyKey: kubernetes.io/hostname
      containers:
      - name: memcached
        image: memcached:1.5.22
        command:
        - memcached
        - -m {{ pluck .Values.global.env .Values.memcached.memory | first | default .Values.memcached.memory._default }}
        - -o
        - modern
        - v
        ports:
        - name: memcached
          containerPort: 11211
        livenessProbe:
          tcpSocket:
            port: memcached
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: memcached
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            cpu: {{ pluck .Values.global.env .Values.resources.memcached.requests.cpu | first | default .Values.resources.memcached.requests.cpu._default }}
            memory: {{ pluck .Values.global.env .Values.resources.memcached.requests.memory | first | default .Values.resources.memcached.requests.memory._default }}
          limits:
            cpu: {{ pluck .Values.global.env .Values.resources.memcached.limits.cpu | first | default .Values.resources.memcached.limits.cpu._default }}
            memory: {{ pluck .Values.global.env .Values.resources.memcached.limits.memory | first | default .Values.resources.memcached.limits.memory._default }}
      - name: exporter
        image: quay.io/prometheus/memcached-exporter:v0.6.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9150
          name: http-metrics
          protocol: TCP
        securityContext:
          runAsUser: 1000
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 256Mi
